/**
 * Represents a single entry in a plant's diary.
 */
export interface DiaryEntry {
  /**
   * Unique identifier for the diary entry.
   */
  id: string;
  /**
   * ID of the plant this entry belongs to.
   */
  plantId: string;
  /**
   * ISO 8601 timestamp of when the entry was created.
   */
  timestamp: string;
  /**
   * ID of the user who created the entry.
   */
  authorId: string; // Consider linking to a User type later
  /**
   * Textual notes or observations.
   */
  note: string;
  /**
   * Growth stage (e.g., Seedling, Vegetative, Flowering, Harvested).
   */
  stage?: string;
  /**
   * Plant height in centimeters.
   */
  heightCm?: number;
  /**
   * Electrical Conductivity (EC) reading.
   */
  ec?: number;
  /**
   * pH level reading.
   */
  ph?: number;
  /**
   * Temperature reading (°C).
   */
  temp?: number;
  /**
   * Humidity reading (%).
   */
  humidity?: number;
  /**
   * URL of an associated photo (optional).
   * In a real app, this might point to cloud storage.
   */
  photoUrl?: string | null;
  /**
   * Summary generated by AI analysis of the photo (optional).
   */
  aiSummary?: string | null;
   /**
   * Raw JSON response from the AI analysis (optional, for debugging/auditing).
   */
   // aiRawJson?: string | null; // Consider adding later if needed
}
